// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package generate

import (
	"database/sql"
)

type Mockdatum struct {
	ID        int32
	FirstName string
	LastName  string
	Email     sql.NullString
	Gender    sql.NullString
	IpAddress sql.NullString
	Date      sql.NullTime
}
